import TrendingCoins from '@/components/CoinDetailPageComponents/TrendingCoins'
import Hero from '@/components/HomePageComponents/Hero'
import HomeComnponent from '@/components/HomePageComponents/Home'
import Navbar from '@/components/HomePageComponents/Navbar'
import { Inter } from 'next/font/google'
import Head from 'next/head'


const inter = Inter({ subsets: ['latin'] })
export default function Home() {

  return (
    <>
      <Head>
        <title>Commune Crypto Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Navbar />
        <Hero />

        <div className=' flex justify-evenly flex-wrap gap-10'>
          <div className=''>
            <TrendingCoins />
            <HomeComnponent />
          </div>

        </div>
      </div>

    </>
  )
}
